# zplug
if [ -f ~/.zplug/init.zsh ]; then
  source ~/.zplug/init.zsh
else
  echo "zplug is not installed. Please install it first."
fi

zplug "themes/clean", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "b4b4r07/enhancd", use:"init.sh"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  echo "Installing missing plugins..."
  zplug install
fi
zplug load

# completion
setopt auto_cd
setopt auto_pushd
setopt correct
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history

# aliases
REPO="~/ghq"
GCCAC="g++ -std=gnu++2b -O2 -Wall -Wextra -I ${REPO}/tic40/atcoder/libraries/ac-library main.cpp"

alias vi='nvim'
alias vim='nvim'
alias ls='ls -G'
alias ll='ls -alGh'
alias repo="cd ${REPO}"
alias tic40="cd ${REPO}/tic40"
alias atc="cd ${REPO}/tic40/atcoder"
alias dotfiles="cd ${REPO}/tic40/dotfiles"
alias gccac="${GCCAC}"
alias gccace="${GCCAC} && ./a.out"
alias runtest="${REPO}/tic40/atcoder/scripts/runTest.sh"

alias cdghq="cd \$(ghq list -p | fzf)"
alias poc-note="cd ${REPO}/pocake/note"
alias poc-notef="cd ${REPO}/pocake/note-front"
alias poc-notef2="cd ${REPO}/pocake/frontend"

alias gpc='gh pr create'
alias gpl='gh pr list --limit 50'
alias gplr='gh pr list --search "review-requested:@me"'
alias gpco='gh pr checkout'
alias gpv='gh pr view'

alias untar='tar -zxvf'
alias wget='wget -c'
alias getpass='openssl rand -base64 20'
alias sha='shasum -a 256'
alias ping='ping -c 5'
alias www='python3 -m http.server'
alias speed='speedtest-cli --server 2406 --simple'
alias ipe='curl ipinfo.io/ip'
alias ipi='ipconfig getifaddr NIC'
alias big10='du -sh ./* | sort -nr | head -n 10'
alias vimlast='ls -tr | tail -n 1 | xargs -o vim'
alias cformat='clang-format -style=file -i'
alias char100='for i in {1..100}; do echo -n 'a'; done'
alias fizzbuzz='for i in {1..100}; do ([ $((i%15)) = 0 ] && echo 'fizzbuzz') || ([ $((i%3)) = 0 ] && echo 'fizz') || ([ $((i%5)) = 0 ] && echo 'buzz') || echo $i; done'
alias dsize='du -sh ./*'
alias wcnt='wc -m'
alias ggrep='git grep'

# Downloads の test\d ファイルをカレントディレクトリに移動する
movetest() {
  find ~/Downloads -type f -name 'test*' -maxdepth 1 | grep -E 'test\d$' | awk '{print $1 " ./"}' | xargs -n 2 mv
}

mkcd() { mkdir $* && cd $_ }

# brew
export PATH=/opt/homebrew/bin:$PATH
# rbenv
eval "$(rbenv init -)"
# nodenv
eval "$(nodenv init - zsh)"
export PATH="$HOME/.nodenv/bin:$PATH"

# for claude code
export PATH="$HOME/.local/bin:$PATH"
